name: Preprocessing

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing
        run: python preprocessing/automate_Kevin-Tanus.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add preprocessing/breast_cancer_cleaned.csv
          git commit -m "Update preprocessed data" || echo "No changes"

          git push
